### ISSUE TITLE
The ability to resize the signature and access the canvas elements.

### ISSUE THREAD

**Issue by kannayash** [keirbowden/sigcapapp#11]
Hi,
    We have a business use case to resize the signature. So, we are trying to access the canvas elements and resize it. But because of the locker service we are not able to access the canvas elements from the managed package. 
We like to know if you can develop a feature to resize the signature or make the canvas elements available to access.

Thanks,
Yash.

**Comment by kannayash** [comment]
Hi, 
   Good Morning.
   Did someone get a chance to address this feature request? Do we have a scope do develop this feature anytime soon? 

Thanks,
Yash.

**Comment by keirbowden** [comment]
Hi Yash,

I won't be able to give you access to the canvas element due to the locker service so this would be a larger change.

Signature capture is a free app that I maintain in my spare time, and at the moment I can't tell you when I'll get a chance to look at it. I doubt it will be until after Dreamforce as I have a number of things to prepare for that.

Cheers

Keir

**Comment by keirbowden** [comment]
Hi Yash,

The Lightning application event that is fired when the signature is captured includes the data URI from the canvas, with the "data:image/png;base64" bit stripped off, which is the contents of the image file. You should be able to apply this to a canvas element of your own to resize the image.

**Comment by keirbowden** [comment]
Closing this as no response for over a year.
