### ISSUE TITLE
Stop the screen scrolling when signing

### ISSUE THREAD

**Issue by SFWannabe** [keirbowden/sigcapapp#22]
Hello, not sure if this is fixed, but i use a surface pro... when i use the pen to sign, nothing signs becasue the screen just scrolls with the pen... can you advise how to fix please?

Working fine on the mobile phone...

**Comment by keirbowden** [comment]
Hi,

Surface Pro isn't a tested platform for us right now, but it's on my list as I recently bought one! 

Also, which browser are you using - we currently don't test against (and therefore expect to support) Edge.

**Comment by SFWannabe** [comment]
Hi,

I have tried Edge, Chrome, IE… when I put the pen on the screen, the pen attempts to scroll the form.
If I hold the button on the surface pro pen – this does allow the signature to write…


Best Regards,

John Wealsby

**Comment by keirbowden** [comment]
Thanks for the info - I'm hoping to have a look at the Surface Pro tomorrow.

**Comment by keirbowden** [comment]
Hi John,

So the underlying issue here is that the Pro "identifies" as a desktop to the lightning experience, but also behaves as a tablet with touch input.  The touch input was being ignored and picked up by the outer Salesforce container, hence scrolling the screen.

I've pushed a new version (2.2) on the app exchange to add Surface Pro support at : https://appexchange.salesforce.com/listingDetail?listingId=a0N30000000q5XOEAY

I've tested on my device using the trackpad in the keyboard cover, touching the screen and with a Microsoft certified pen, on Chrome and Edge Chromium, and I can sign as expected in all cases.

Can you give this a try and let me know if you have any further issues.

Cheers

--

Keir

**Comment by SFWannabe** [comment]
Hi Keir,

Sounds like the Pro is working well for you…

I tested the update and all is working as expected – great thankyou.
I have the Pro 4 and tested with Chrome and MS pen…

Should the signature be retained in the captured signature place holder?
It does while I stay in the object and move to details tab, related tab etc…
But if I refresh the page, the signature tab is blank again.

My ultimate goal is to get the signature to a PDF document… I’m getting there…

But yes, its working much better – thankyou.

Best Regards,

John Wealsby

**Comment by keirbowden** [comment]
The page refresh is by design - the assumption is that you want to overwrite the previous signature if you go to the same page.
